version: 1.0.{build}
image: Visual Studio 2017
skip_non_tags: true
environment:
 DOCKER_USER:
  secure: pbQKStRwGMl6RTDva4sLxw==
 DOCKER_PASS:
  secure: jmD9um0U9uJ9uKmAASvz3wxR4IYFU9bCc4N9mgMcX28=
build_script:
- ps: >-
    cd servercore

    docker build -t roberterez/octopusdocker:${env:APPVEYOR_REPO_TAG_NAME}-servercore .

test_script:
- ps: >-
    docker run roberterez/octopusdocker:${env:APPVEYOR_REPO_TAG_NAME}-servercore version
deploy_script:
- ps: >-
    docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"

    docker push roberterez/octopusdocker:${env:APPVEYOR_REPO_TAG_NAME}-servercore